services:
  movie.search_filter:
    parent: 'api_platform.doctrine.orm.search_filter'
    arguments: [ { id: 'exact', title: 'partial', description: 'partial', category: 'exact' } ]
    tags: ['api_platform.filter']