api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    collection:
        pagination:
            client_enabled: true
            items_per_page: 10
            page_parameter_name: pagina
            client_items_per_page: true #itemsPerPage=20
            items_per_page_parameter_name: itensPorPagina
    eager_loading:
        enabled: false